# Configurations for the project
data:
  source: "yfinance"
  tickers: ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NFLX", "META", "IBM"]
  start_date: "2018-01-01"
  end_date: "2023-01-01"
  frequency: "1d"
  moving_average_windows: [25, 50, 75, 100, 125, 150, 175, 200]
  technical_indicators: ["SMA", "EMA", "RSI"]

paths:
  raw_data_paths: "data/raw/"
  processed_data_paths: "data/processed/"
  notebooks: "notebooks/"
  scripts: "scripts/"
  tests: "tests/"
  logs: "logs/"
  models: "models/"

backtest:
  start_date: "2020-01-01"
  end_date: "2023-01-01"
  initial_capital: 100000
  commission: 0.001
  slippage: 0.001
  max_drawdown: 0.1
  rebalance_frequency: "1m"

strategy: 
  type: "mean_reversion"
  lookback_period: 90
  entry_threshold: 1.0
  exit_threshold: 0.5
  position_sizing: "fixed"
  max_positions: 5
  stop_loss: 0.02
  
